
  
version: '2.3'
services:
  perseption_camera:
    build:
      context: perception_camera
      dockerfile: Dockerfile
    tty: true
    container_name: perception_camera_container
    environment:
      - HOST_IP=192.168.0.199
    restart: on-failure

