
  
version: '2.3'
services:
  bridge:
    build:
      context: bridge
      dockerfile: Dockerfile
    container_name: bridge_container

  perception_nodes:
    build:
      context: perception_nodes
      dockerfile: Dockerfile
    container_name: perception_nodes_container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    privileged: true