
  
version: '2.3'
services:
  perception_nodes:
    build:
      context: perception_nodes
      dockerfile: Dockerfile
    command: roscore
    network_mode: host
    container_name: perception_nodes_container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_MASTER_URI=http://127.0.0.1:11311
      - ROS_IP=127.0.0.1
    privileged: true
    restart: on-failure

  bridge:
    build:
      context: bridge
      dockerfile: Dockerfile
    command: ros2 run ros1_bridge dynamic_bridge
    network_mode: host
    container_name: bridge_container
    depends_on: 
      - perception_nodes
    environment:
      - ROS_MASTER_URI=http://127.0.0.1:11311
      - ROS_IP=127.0.0.1
      - ROS_DOMAIN_ID=0
    restart: on-failure